################################################################################################################################################
# Fortify lets you build secure software fast with an appsec platform that automates testing throughout the DevSecOps pipeline. Fortify static,#
# dynamic, interactive, and runtime security testing is available on premises or as a service. To learn more about Fortify, start a free trial #
# or contact our sales team, visit microfocus.com/appsecurity.                                                                                 #
#                                                                                                                                              #
# Use this workflow template as a basis for integrating Fortify on Demand Static Application Security Testing(SAST) into your GitHub workflows.#
# This template demonstrates the steps to prepare the code+dependencies, initiate a scan, download results once complete and import into       #
# GitHub Security Code Scanning Alerts. Existing customers should review inputs and environment variables below to configure scanning against  #
# an existing application in your Fortify on Demand tenant. Additional information is available in the comments throughout the workflow, the   #
# documentation for the Fortify actions used, and the Fortify on Demand / ScanCentral Client product documentation. If you need additional     #
# assistance with configuration, feel free to create a help ticket in the Fortify on Demand portal.                                            #
################################################################################################################################################

name: Fortify SCA Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:  # 👈 This enables manual runs from GitHub UI

jobs:
  fortify-scan:
    runs-on: [self-hosted, Windows, X64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Fortify SCA Translation
      run: |
        "C:\Program Files\Fortify\Fortify_SCA_24.4.0\bin\sourceanalyzer.exe" -b myApp -clean
        "C:\Program Files\Fortify\Fortify_SCA_24.4.0\bin\sourceanalyzer.exe" -b myApp -Xmx4G -debug -verbose -scan -f myApp.fpr .

    - name: Upload FPR to SSC
      run: |
        "C:\Program Files\Fortify\Fortify_SCA_24.4.0\bin\fortifyclient.bat" uploadFPR -url https://localhost:8443/ssc -authtoken f783e7d6-ee0e-4846-bed7-adcc8d767bab -project "github-action" -version "1" -file myApp.fpr

    - name: Check FPR exists
      run: |
        if not exist myApp.fpr (
          echo "FPR file was not created!"
          exit 1
        )
